platform :ios, '10.0'
target 'FriendlyPix' do
  use_frameworks!

  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/MLVision'
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Anonymous'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'ImagePicker'
  pod 'Lightbox'
  pod 'MaterialComponents/BottomAppBar'
  pod 'MaterialComponents/Buttons+ColorThemer'
  pod 'MaterialComponents/Collections'
  pod 'MaterialComponents/Dialogs'
  pod 'MaterialComponents/Dialogs+ColorThemer'
  pod 'MaterialComponents/Snackbar'
  pod 'MaterialComponents/TextFields'
  pod 'MaterialComponents/List'
  pod 'SDWebImage'
pod 'FirebaseMLVision'
pod 'FirebaseMLCommon'
pod 'FirebaseMLModelInterpreter'
pod 'FirebaseMLVisionFaceModel'
pod 'FirebaseMLVisionBarcodeModel'
pod 'FirebaseMLVisionLabelModel'
pod 'FirebaseMLVisionTextModel'
end
