target 'FriendlyPix' do
  use_frameworks!

  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Invites', '5.7.0'
  pod 'Firebase/Messaging'
  pod 'Firebase/MLVision'
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/Google'
  pod 'GoogleSignIn', '4.1.2'
  pod 'ImagePicker'
  pod 'Lightbox'
  pod 'MaterialComponents/BottomAppBar'
  pod 'MaterialComponents/Buttons+ColorThemer'
  pod 'MaterialComponents/Collections'
  pod 'MaterialComponents/Dialogs'
  pod 'MaterialComponents/Snackbar'
  pod 'MaterialComponents/TextFields'
  pod 'SDWebImage'
end
