platform :ios, '10.0'
target 'FriendlyPix' do
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/MLVision'
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Anonymous'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'ImagePicker'
  pod 'Lightbox'
  pod 'MaterialComponents/BottomAppBar'
  pod 'MaterialComponents/Buttons+ColorThemer'
  pod 'MaterialComponents/Cards'
  pod 'MaterialComponents/Chips'
  pod 'MaterialComponents/Dialogs'
  pod 'MaterialComponents/Dialogs+ColorThemer'
  pod 'MaterialComponents/Snackbar'
  pod 'MaterialComponents/TextFields'
  pod 'MaterialComponents/List'
  pod 'SDWebImage'
end
